# Generated by Django 6.0.3 on 2026-03-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especificacoes', models.TextField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('MANUTENCAO', 'Em Manutenção'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aquisicao', models.DateField()),
            ],
        ),
    ]
